### ISSUE TITLE
Missing Source Code

### ISSUE THREAD

**Issue by jgeboski** [alexfoster/NaiveBayes#1]
As stated by the [GPLv3](https://www.gnu.org/licenses/quick-guide-gplv3.en.html), everyone should be entitled to four freedoms. I am hoping to deploy freedom two, _the freedom to change the software to suit your needs_. In order to do this, I need to obtain a copy of the source code. Are there any intentions of putting the source on GitHub?

**Comment by alexfoster** [comment]
If you would like the full source code, please answer the following question: You got paypal?
